version: '3' 
services:
    redis_db:
        image: "redis"
        volumes:
            - ./data:/data
        command: ["redis-server","--save","1 1"]
    node-app:
        build: ./
        image: "devikaravi/visits"
        ports:
            - "8081:8081"
